src/web/WM.WebApp.MVC/Controllers/AnunciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WM.WebApp.MVC;
using WM.WebApp.MVC.Models;
using WM.WebApp.MVC.Models.DTO;
using WM.WebApp.MVC.Services;

namespace WM.WebApp.MVC.Controllers
{
    public class AnunciosController : Controller
    {
        private readonly IVitrineService _vitrineService;
        private readonly IMapper _mapper;
        public AnunciosController(IVitrineService vitrineService,
                                  IMapper mapper)
        {
            _vitrineService = vitrineService;
            _mapper = mapper;
        }

        // GET: Anuncios
        public async Task<IActionResult> Index()
        {
            return View(await _vitrineService.Get());
        }

        // GET: Anuncios/Create
        public async Task<IActionResult> Create()
        {
            var anunciosViewModel = new AnunciosViewModel
            {
                Makes = await _vitrineService.GetMake()
            };

            return View(anunciosViewModel);
        }

        // POST: Anuncios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Make,Model,Version,Year,Mileage,Note")] AnunciosViewModel anunciosViewModel)
        {
            if (ModelState.IsValid)
            {
                var anuncios = _mapper.Map<AnunciosDTO>(anunciosViewModel);

                await _vitrineService.Create(anuncios);

                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Anuncios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anunciosViewModel = await _vitrineService.GetId(id ?? 0);
            if (anunciosViewModel == null)
            {
                return NotFound();
            }

            return View(anunciosViewModel);
        }

        // POST: Anuncios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Make,Model,Version,Year,Mileage,Note")] AnunciosViewModel anunciosViewModel)
        {
            if (id != anunciosViewModel.Id) return NotFound();

            if (!ModelState.IsValid) return View(anunciosViewModel);

            try
            {
                if (ModelState.IsValid)
                {
                    var anuncio = _mapper.Map<AnunciosDTO>(anunciosViewModel);

                    await _vitrineService.Edit(anuncio);

                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch (DbUpdateConcurrencyException)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Anuncios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anunciosViewModel = await _vitrineService.GetId(id ?? 0);

            if (anunciosViewModel == null)
            {
                return NotFound();
            }

            return View(anunciosViewModel);
        }

        // POST: Anuncios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _vitrineService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> GetModels(int id)
        {
            return Json(await _vitrineService.GetModels(id));
        }

        public async Task<IActionResult> GetVehicles(int id)
        {
            return Json(await _vitrineService.GetVehicles(id));
        }

        public async Task<IActionResult> GetVersion(int id)
        {
            return Json(await _vitrineService.GetVersion(id));
        }
    }
}

src/web/WM.WebApp.MVC/Controllers/VitrineController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WM.WebApp.MVC.Models;
using WM.WebApp.MVC.Services;

namespace WM.WebApp.MVC.Controllers
{
    public class VitrineController : Controller
    {
        private readonly IVitrineService _vitrineService;

        public VitrineController(IVitrineService vitrineService)
        {
            _vitrineService = vitrineService;
        }

        public async Task<ActionResult> Index()
        {
            return View(await _vitrineService.GetVehicles(1));
        }

        public async Task<ActionResult> VitrineDetalhe()
        {
            return View(await _vitrineService.GetVehicles(1));
        }
    }
}

src/web/WM.WebApp.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewData["Title"] - NerdStore Enterprise</title>
    
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">
    <link href="~/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/css/responsive.css" rel="stylesheet" />

</head>
<body>

    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-4">
                        <a asp-action="Index" asp-controller="Vitrine" class="brand-wrap" style="margin-left: 20%;">
                            <img alt="Web Motors" class="logo" src="~/images/logo.svg">
                        </a>
                    </div>
                    <div class="col-lg-8 col-sm-12">
                        <form method="get" class="search" style="width: 70%;  float: left;" >
                            <div class="input-group w-100">
                                <input type="text" id="q" name="q" class="form-control" placeholder="O que você está procurando?">
                                <div class="input-group-append">
                                    <button class="btn btn-danger" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <a asp-action="Index" asp-controller="Anuncios" 
                            style=" width: 20%; float: right; text-align: center; background-color: #f3123c; box-shadow: 0 8px 12px -8px #f3123c; border-radius: 8px; font-size: 16px; font-weight: 500; text-align: center; letter-spacing: .04em; color: #fff; border-radius: 8px; padding: 0 8px; display: -webkit-box; display: -webkit-flex; display: -ms-flexbox; display: flex; -webkit-box-align: center; -webkit-align-items: center; -ms-flex-align: center; align-items: center; -webkit-box-pack: center; -webkit-justify-content: center; -ms-flex-pack: center; justify-content: center; margin: 0; border: 0; height: 40px; -webkit-box-sizing: border-box; box-sizing: border-box; -webkit-appearance: none; -moz-appearance: none; appearance: none; cursor: pointer;" 
                            type="submit">
                            Novo Anuncio
                        </a>
                    </div>
                   
                </div>   
            </div>   
        </section>    



    </header>
    <div>
            @RenderBody()
    </div>

    <footer class="section-footer border-top">
        <div class="container">
            <section class="footer-top padding-y">
                <div class="row">
                    <aside class="col-md-4">
                        <article class="mr-3">
                            <img src="~/images/logo.svg" class="logo-footer">
                            <div>
                                <a class="btn btn-icon btn-light" title="Facebook" target="_blank" href="#"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-icon btn-light" title="Instagram" target="_blank" href="#"><i class="fab fa-instagram"></i></a>
                                <a class="btn btn-icon btn-light" title="Youtube" target="_blank" href="#"><i class="fab fa-youtube"></i></a>
                                <a class="btn btn-icon btn-light" title="Twitter" target="_blank" href="#"><i class="fab fa-twitter"></i></a>
                            </div>
                        </article>
                    </aside>
                    <aside class="col-sm-4 col-md-3">
                        <h6 class="title">Sobre</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Sobre nós</a></li>
                            <li> <a href="#">Serviços</a></li>
                            <li> <a href="#">Termo de Uso</a></li>
                            <li> <a href="#">FAQ</a></li>
                        </ul>
                    </aside>
                    <aside class="col-sm-4 col-md-3">
                        <h6 class="title">Serviços</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Meus Pedidos</a></li>
                            <li> <a href="#">Meu Perfil</a></li>
                            <li> <a href="#">Cancelamentos</a></li>
                            <li> <a href="#">Reembolsos</a></li>
                        </ul>
                    </aside>
                    <aside class="col-sm-2  col-md-2">
                        <h6 class="title">Mobile</h6>
                        <a href="#" class="d-block mb-2"><img src="~/images/misc/appstore.png" height="40"></a>
                        <a href="#" class="d-block mb-2"><img src="~/images/misc/playmarket.png" height="40"></a>
                    </aside>
                </div>   
            </section>	  
        </div>  
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <script src="~/js/script.js" type="text/javascript"></script>
    <script src="~/js/site.js" type="text/javascript"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>